### ISSUE TITLE
背景画像の設定

### ISSUE THREAD

**Issue by stshf** [Recursion-teamdev-go-lang-teamc/space-app#7]
## 📋 説明

宇宙っぽい背景画像に設定し、背景画像をいつでも変更できる状態にしておく

- [x] 背景画像の設定方法を調査
  cssで制御する場合
  ```css
  body {
    background-img:url("相対パス")
  }
  ```
  bodyはほかのタグでも適用可能
- [x] Webで背景画像を入手
  -> いったんPixabayより入手した
- [x] 背景画像をhtmlに反映
- [x] 背景画像と対照的なフォントカラーに設定
  -> whiteに設定
## 受け入れ条件（完了の定義）

- [ ] ブラウザ上で背景画像が確認できること
